/**
 * YOJANAI — demo scheme catalogue (v1).
 * Realistic demo records for Tamil Nadu + central government schemes relevant
 * to small business owners, with awareness levels so the platform can surface
 * lesser-known opportunities. Details are prototype data — in production every
 * record is verified against the official source before display.
 */
import type { Rule, Scheme } from "./eligibility";

/** Compact rule helper. */
function r(
  field: Rule["field"],
  op: Rule["op"],
  value: Rule["value"],
  weight: number,
  when: string,
  fix?: string,
): Rule {
  return { field, op, value, weight, when, fix };
}

export const SCHEME_SEED: Scheme[] = [
  {
    id: "pmegp",
    name: "PMEGP — Prime Minister's Employment Generation Programme",
    department: "Ministry of MSME · KVIC",
    level: "central",
    sector: "Micro enterprise",
    tags: ["start_business", "business_loan", "financial_assistance"],
    summary:
      "Margin-money subsidy on bank loans for new micro enterprises. The government pays 35% of the project cost for rural SC/ST/OBC/PH/women (25% urban), and 15% for others — you fund the rest.",
    benefit:
      "Capital subsidy of 15–35% of project cost (up to ₹25L manufacturing / ₹10L service projects), plus a collateral-free bank loan for the balance.",
    loanWindow: { min: 0.25, max: 25, rate: 8, subsidy: 25, tenureMax: 7 },
    eligibilityText:
      "New business, age 18+, any category. Manufacturing projects up to ₹25L, service projects up to ₹10L.",
    documents: ["business_plan", "photo", "community_certificate", "bank_passbook", "udyam"],
    applicationRoute: "Apply online at the KVIC portal (kviconline.gov.in) → District Industries Centre approves.",
    officialSource: "MSME · KVIC",
    sourceUrl: "https://www.kviconline.gov.in",
    helpdesk: "KVIC helpdesk / District Industries Centre",
    awareness: "known",
    verifiedDate: "2026-08",
    rules: [
      r("age", "gte", 18, 20, "You are at least 18 years old"),
      r("projectCost", "lte", 25, 20, "Project cost within the ₹25L limit"),
      r("category", "in", ["SC", "ST", "OBC", "EBC", "DNT"], 10, "Reserved category gets the higher 35%/25% subsidy band"),
      r("hasExistingBusiness", "truthy", undefined, 10, "Preference for first-time entrepreneurs is waived — existing units can expand"),
      r("businessType", "nin", ["startup"], 5, "Traditional micro-enterprise sectors are covered"),
    ],
  },
  {
    id: "mudra",
    name: "PMMY — MUDRA Loan (Shishu / Kishor / Tarun)",
    department: "Ministry of Finance · SIDBI",
    level: "central",
    sector: "Business finance",
    tags: ["business_loan", "start_business", "financial_assistance"],
    summary:
      "Collateral-free loans up to ₹10 lakh for non-farm income-generating activities: ₹50k Shishu, up to ₹5L Kishor, up to ₹10L Tarun.",
    benefit: "Loans up to ₹10L with no collateral and no processing fees, available from any bank / NBFC / MFI.",
    loanWindow: { min: 0.05, max: 10, rate: 8.5, subsidy: 0, tenureMax: 5 },
    eligibilityText: "Any income-generating activity (existing or new), age 18+. No collateral needed.",
    documents: ["business_plan", "bank_passbook", "udyam", "aadhaar"],
    applicationRoute: "Any commercial / regional rural bank branch, or online through the MUDRA portal's bank links.",
    officialSource: "MUDRA · SIDBI",
    sourceUrl: "https://www.mudra.org.in",
    helpdesk: "MUDRA helpline / nearest bank branch",
    awareness: "known",
    verifiedDate: "2026-08",
    rules: [
      r("age", "gte", 18, 15, "You are at least 18 years old"),
      r("projectCost", "lte", 10, 20, "Requirement within the ₹10L MUDRA ceiling"),
      r("hasExistingBusiness", "truthy", undefined, 15, "Existing businesses can apply for the higher Kishor / Tarun slabs"),
      r("businessType", "nin", ["startup"], 5, "Any non-farm activity qualifies — retail, food, services, tailoring"),
    ],
  },
  {
    id: "standup",
    name: "Stand-Up India",
    department: "Ministry of Finance · SIDBI",
    level: "central",
    sector: "Enterprise finance",
    tags: ["start_business", "womens_entrepreneurship", "business_loan"],
    summary:
      "Bank loans between ₹10 lakh and ₹1 crore for greenfield enterprises promoted by SC/ST and/or women entrepreneurs — one per borrower, per branch.",
    benefit: "Composite loan ₹10L–₹1Cr (75% term loan + 25% working capital), no collateral if covered by CGTMSE, lowest-ever interest + 8-week moratorium on term loans.",
    loanWindow: { min: 10, max: 100, rate: 9, subsidy: 0, tenureMax: 7 },
    eligibilityText: "Greenfield enterprise by a SC/ST and/or woman entrepreneur, age 18+.",
    documents: ["business_plan", "community_certificate", "bank_passbook", "udyam", "photo"],
    applicationRoute: "Online via standupmitra.in — the portal routes you to a bank branch that serves your location.",
    officialSource: "Stand-Up India · SIDBI",
    sourceUrl: "https://www.standupmitra.in",
    helpdesk: "Stand-Up Mitra helpline / lead bank manager",
    awareness: "known",
    verifiedDate: "2026-08",
    rules: [
      r("gender", "eq", "female", 15, "Woman entrepreneur"),
      r("category", "in", ["SC", "ST"], 15, "SC/ST entrepreneur"),
      r("age", "gte", 18, 10, "You are at least 18 years old"),
      r("projectCost", "gte", 10, 20, "Funding requirement is in the ₹10L–₹1Cr band"),
      r("hasExistingBusiness", "falsy", undefined, 15, "Greenfield (new) enterprise"),
    ],
  },
  {
    id: "vishwakarma",
    name: "PM Vishwakarma",
    department: "Ministry of MSME",
    level: "central",
    sector: "Artisan & craft",
    tags: ["skill_training", "start_business", "financial_assistance"],
    summary:
      "End-to-end support for traditional artisans and crafts-persons — skill certificates, toolkits, and a ₹1 lakh collateral-free loan at 5% with 100% interest subvention by the government.",
    benefit: "Recognition certificate, skill training + ₹500/day stipend, toolkit, ₹1L loan at 0% effective interest (5% rate, fully subvented) with 18-month tenure.",
    loanWindow: { min: 0.05, max: 1, rate: 5, subsidy: 100, tenureMax: 1.5 },
    eligibilityText: "Traditional trades only (e.g. carpenter, blacksmith, tailor, potter), age 18+, must be practising the trade.",
    documents: ["aadhaar", "photo", "bank_passbook"],
    applicationRoute: "Apply at the nearest Common Service Centre (CSC) or online at pmvishwakarma.gov.in.",
    officialSource: "Ministry of MSME",
    sourceUrl: "https://pmvishwakarma.gov.in",
    helpdesk: "CSC / district MSME office",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("businessType", "in", ["tailoring", "carpentry", "blacksmith", "pottery", "handicraft"], 25, "Your trade is in the 18 recognised Vishwakarma trades"),
      r("age", "gte", 18, 15, "You are at least 18 years old"),
      r("hasExistingBusiness", "truthy", undefined, 15, "You currently practise the trade"),
      r("age", "lte", 60, 10, "Age within the 18–60 band"),
    ],
  },
  {
    id: "sisfs",
    name: "Startup India Seed Fund Scheme (SISFS)",
    department: "DPIIT · Startup India",
    level: "central",
    sector: "Startup",
    tags: ["start_business", "financial_assistance", "business_loan"],
    summary:
      "Financial support of up to ₹50 lakh (₹20L for validation + ₹30L for market-entry) for ideas at proof-of-concept, prototype or product stage through approved incubators.",
    benefit: "Seed capital up to ₹50L — no collateral, no early-stage equity dilution (convertible debentures / loans).",
    loanWindow: { min: 5, max: 50, rate: 1, subsidy: 0, tenureMax: 10 },
    eligibilityText:
      "DPIIT-recognised startup (recognise free at startupindia.gov.in) with a strong idea, incubated through an approved incubator.",
    documents: ["business_plan", "seed_stage_pitch", "udyam"],
    applicationRoute: "Get recognised on startupindia.gov.in → apply through a DPIIT-approved incubator (e.g. IIT / REC incubators).",
    officialSource: "DPIIT · Startup India",
    sourceUrl: "https://www.startupindia.gov.in",
    helpdesk: "Startup India helpdesk",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("businessType", "eq", "startup", 25, "You are building a startup (proof-of-concept stage)"),
      r("projectCost", "gte", 10, 15, "Seed requirement of ₹10L or more"),
      r("hasExistingBusiness", "truthy", undefined, 10, "Company incorporated — needed for DPIIT recognition"),
    ],
  },
  {
    id: "cgtmse",
    name: "CGTMSE — Credit Guarantee Fund for Micro & Small Enterprises",
    department: "Ministry of MSME · CGTMSE",
    level: "central",
    sector: "Business finance",
    tags: ["business_loan", "financial_assistance", "start_business"],
    summary:
      "Not a loan itself — it is the guarantee that lets banks lend to MSMEs with NO collateral and NO third-party guarantee, covering up to 85% of loans up to ₹2 crore.",
    benefit: "Collateral-free credit up to ₹2Cr with guarantee cover of 75–85%; female / rural micro enterprises get the highest 85% cover.",
    loanWindow: { min: 1, max: 200, rate: 8, subsidy: 0, tenureMax: 5 },
    eligibilityText: "Any existing or new micro/small enterprise (Udyam registered), loan up to ₹2Cr.",
    documents: ["udyam", "bank_passbook", "business_plan"],
    applicationRoute: "Ask any bank for a 'CGTMSE-covered' loan — the bank files the guarantee on your behalf. No separate application.",
    officialSource: "CGTMSE · Ministry of MSME",
    sourceUrl: "https://www.cgtmse.in",
    helpdesk: "CGTMSE Mumbai office / your bank's MSME desk",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("hasExistingBusiness", "truthy", undefined, 20, "Existing business can access the guarantee immediately"),
      r("projectCost", "lte", 200, 15, "Loan requirement within ₹2Cr cover limit"),
      r("age", "gte", 18, 10, "You are at least 18 years old"),
    ],
  },
  {
    id: "nsfdc",
    name: "NSFDC — Concessional Loans for SC Entrepreneurs",
    department: "Ministry of Social Justice · NSFDC",
    level: "central",
    sector: "Enterprise finance",
    tags: ["start_business", "business_loan", "financial_assistance"],
    summary:
      "Low-interest loans for Scheduled Caste entrepreneurs with family income up to ₹3 lakh — up to ₹40 lakh for manufacturing, ₹25 lakh for services through state channelising agencies.",
    benefit: "Concessional interest (≈4–6% p.a.), soft-loan terms, and linkage to capital subsidy programmes like PM-AJAY.",
    loanWindow: { min: 0.5, max: 40, rate: 4.5, subsidy: 0, tenureMax: 10 },
    eligibilityText: "SC beneficiary, age 18–55, family income ≤ ₹3L (some states ₹5L), viable project.",
    documents: ["community_certificate", "income_certificate", "business_plan", "bank_passbook", "photo"],
    applicationRoute: "Via your State Channelising Agency (TN: TAHDCO) — apply through its district office or online portal.",
    officialSource: "NSFDC · Ministry of Social Justice & Empowerment",
    sourceUrl: "https://www.nsfdc.nic.in",
    helpdesk: "NSFDC regional office / state channelising agency",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("category", "eq", "SC", 25, "Scheduled Caste beneficiary (community certificate)"),
      r("age", "gte", 18, 5, "You are at least 18 years old"),
      r("age", "lte", 55, 5, "Age within 55 years"),
      r("annualFamilyIncome", "lte", 300000, 20, "Family income within the ₹3L ceiling"),
    ],
  },
  {
    id: "nhfdc",
    name: "NHFDC — Loans for Entrepreneurs with Disabilities",
    department: "Ministry of Social Justice · NHFDC",
    level: "central",
    sector: "Enterprise finance",
    tags: ["disability_support", "start_business", "business_loan"],
    summary:
      "Loans up to ₹25 lakh for income-generating activities by persons with disabilities (40%+ disability), with concessional rates and soft repayment terms.",
    benefit: "Up to ₹25L at concessional interest (≈5–6% p.a.) for self-employment, transport, or micro-enterprise activities.",
    loanWindow: { min: 0.5, max: 25, rate: 5.5, subsidy: 0, tenureMax: 10 },
    eligibilityText: "Person with disability (40%+), age 18–65, viable income-generating project; income ≤ ₹3L for the poorest slabs.",
    documents: ["disability_certificate", "community_certificate", "income_certificate", "business_plan", "bank_passbook"],
    applicationRoute: "Through the State Channelising Agency (TN: TAHDCO / TNSC) — district offices accept applications.",
    officialSource: "NHFDC · Ministry of Social Justice & Empowerment",
    sourceUrl: "https://www.nhfdc.nic.in",
    helpdesk: "NHFDC / state channelising agency",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("hasDisability", "truthy", undefined, 30, "You hold a disability certificate (40%+)"),
      r("age", "gte", 18, 5, "You are at least 18 years old"),
      r("age", "lte", 65, 5, "Age within 65 years"),
      r("annualFamilyIncome", "lte", 300000, 15, "Family income within ₹3L for the concessional slab"),
    ],
  },
  {
    id: "pmdaksh",
    name: "PM-DAKSH — Skill Empowerment of SC/ST/OBC",
    department: "Ministry of Social Justice · MoSJE",
    level: "central",
    sector: "Skill training",
    tags: ["skill_training", "financial_assistance", "start_business"],
    summary:
      "Free up-skilling and reskilling for SC/ST/OBC communities — with placement support and stipends, plus entrepreneurship orientation for those ready to start.",
    benefit: "Free skill training (3 months – 1 year), stipend during training, certification and placement assistance.",
    loanWindow: undefined,
    eligibilityText: "SC/ST/OBC (and EBC) applicants, age 18–45, family income ≤ ₹3L.",
    documents: ["community_certificate", "income_certificate", "photo", "education_certificates"],
    applicationRoute: "Apply at the nearest empanelled training institute or online via the PM-DAKSH portal.",
    officialSource: "Ministry of Social Justice & Empowerment",
    sourceUrl: "https://pmdaksh.dosje.gov.in",
    helpdesk: "PM-DAKSH portal helpdesk / district social welfare office",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("category", "in", ["SC", "ST", "OBC"], 30, "SC/ST/OBC community"),
      r("age", "gte", 18, 5, "You are at least 18 years old"),
      r("age", "lte", 45, 5, "Age within 45 years"),
      r("annualFamilyIncome", "lte", 300000, 15, "Family income within the ₹3L ceiling"),
    ],
  },
  {
    id: "tahdco",
    name: "TAHDCO — Self-Employment Loans for SC/ST (TN)",
    department: "Government of Tamil Nadu · TAHDCO",
    level: "state",
    sector: "Enterprise finance",
    tags: ["start_business", "business_loan", "financial_assistance"],
    summary:
      "Tamil Nadu's state channelising agency finances SC/ST entrepreneurs with concessional loans plus capital subsidy under PM-AJAY — often combined with NSFDC funding.",
    benefit: "Project subsidy of 25% (up to ₹2L, 30% for women) + concessional loan up to ₹60L for transport, trade, service or manufacturing units.",
    loanWindow: { min: 0.5, max: 60, rate: 6, subsidy: 25, tenureMax: 7 },
    eligibilityText: "SC/ST entrepreneur based in Tamil Nadu, age 18+, viable project; BPL beneficiaries get priority.",
    documents: ["community_certificate", "income_certificate", "business_plan", "bank_passbook", "photo", "udyam"],
    applicationRoute: "District TAHDCO office (via DIC) or the TAHDCO online application system.",
    officialSource: "TAHDCO · Govt. of Tamil Nadu",
    sourceUrl: "https://taahdco.tn.gov.in",
    helpdesk: "District TAHDCO office / helpline 1800-425-3667",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("category", "in", ["SC", "ST"], 30, "SC/ST category (community certificate)"),
      r("state", "eq", "Tamil Nadu", 15, "Based in Tamil Nadu"),
      r("age", "gte", 18, 10, "You are at least 18 years old"),
      r("annualFamilyIncome", "lte", 300000, 10, "Family income within the priority BPL band"),
    ],
  },
  {
    id: "mannin_magal",
    name: "Mannin Magal Thittam — Land for SC/ST Women",
    department: "Government of Tamil Nadu · Adi Dravidar & Tribal Welfare",
    level: "state",
    sector: "Land & agriculture",
    tags: ["agriculture", "womens_entrepreneurship"],
    summary:
      "A lesser-known TN scheme that purchases agricultural land in the name of SC/ST women from landless families — the land becomes the asset she farms or leases; includes fencing and grant components.",
    benefit: "Land purchase support (up to 0.5 acre, value as per guideline) registered in the woman's own name, plus fencing, land development and a small cultivation grant.",
    loanWindow: undefined,
    eligibilityText: "SC/ST woman from a landless family, resident of Tamil Nadu, interested in farming.",
    documents: ["community_certificate", "income_certificate", "photo", "bank_passbook"],
    applicationRoute: "Apply through the District Adi Dravidar & Tribal Welfare Office / local village panchayat.",
    officialSource: "Adi Dravidar & Tribal Welfare Dept · Govt. of Tamil Nadu",
    sourceUrl: "https://www.tn.gov.in",
    helpdesk: "District Adi Dravidar & Tribal Welfare Officer",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("gender", "eq", "female", 25, "Woman applicant"),
      r("category", "in", ["SC", "ST"], 25, "SC/ST community"),
      r("state", "eq", "Tamil Nadu", 15, "Resident of Tamil Nadu"),
      r("ownsLand", "falsy", undefined, 15, "Landless family — the scheme buys land for you"),
      r("interestedFarming", "truthy", undefined, 10, "You want to farm the land"),
    ],
  },
  {
    id: "vetri_thozhil",
    name: "Vetri Thozhil Munaivor Thittam (TN)",
    department: "Government of Tamil Nadu · Labour & Employment",
    level: "state",
    sector: "Employment",
    tags: ["skill_training", "start_business"],
    summary:
      "Tamil Nadu's job-grant scheme: the government reimburses 40% of the salary of young employees (age 18–35) for up to 3 years — a subsidy that small employers can claim for hiring, and a job-support grant for first-time job seekers.",
    benefit: "40% salary contribution paid directly to the employee's bank account for up to 3 years (₹7,500–₹11,250/month depending on qualification).",
    loanWindow: undefined,
    eligibilityText: "Tamil Nadu resident, age 18–35, employed in the private / industrial / IT sectors; no benefit if already covered by EPFO for 18+ months.",
    documents: ["community_certificate", "education_certificates", "photo", "bank_passbook"],
    applicationRoute: "Apply online at the Tamil Nadu e-Sevai / employment portal; employers can support the claim.",
    officialSource: "Labour & Employment Dept · Govt. of Tamil Nadu",
    sourceUrl: "https://www.tn.gov.in",
    helpdesk: "District employment exchange",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("state", "eq", "Tamil Nadu", 25, "Resident of Tamil Nadu"),
      r("age", "gte", 18, 10, "You are at least 18 years old"),
      r("age", "lte", 35, 15, "Age within 35 years"),
      r("category", "in", ["SC", "ST", "OBC", "EBC", "DNT"], 10, "Reserved category gets priority processing"),
      r("hasExistingBusiness", "falsy", undefined, 10, "Aimed at job seekers / first-time employees"),
    ],
  },
  {
    id: "pudhumai_penn",
    name: "Pudhumai Penn — TN Girls' Education Support",
    department: "Government of Tamil Nadu · School Education",
    level: "state",
    sector: "Education",
    tags: ["scholarship", "higher_education", "womens_entrepreneurship"],
    summary:
      "Monthly financial assistance for girl students in Tamil Nadu (Class 6 to post-school) from government / aided institutions — ₹1,000/month for school, ₹1,500+ for college, credited directly to her account.",
    benefit: "₹1,000/month (classes 6–12), ₹1,500/month (ITI/diploma/degree) — direct benefit transfer to the girl's account.",
    loanWindow: undefined,
    eligibilityText: "Girl student studying in a TN government/aided school or college after 2022–23, family not income-certified as high-income.",
    documents: ["education_certificates", "community_certificate", "bank_passbook", "photo"],
    applicationRoute: "Schools nominate students; families confirm on the Pudhumai Penn portal / Kalvi TV helpline.",
    officialSource: "School Education Dept · Govt. of Tamil Nadu",
    sourceUrl: "https://pudhumaipenn.tn.gov.in",
    helpdesk: "District education office / school head",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("gender", "eq", "female", 30, "Girl student"),
      r("state", "eq", "Tamil Nadu", 20, "Studying in Tamil Nadu"),
      r("category", "in", ["SC", "ST", "OBC", "EBC", "DNT"], 10, "Reserved category priority"),
      r("firstGraduate", "truthy", undefined, 5, "First-generation learner gets priority"),
    ],
  },
  {
    id: "nos",
    name: "National Overseas Scholarship (SC students)",
    department: "Ministry of Social Justice · MoSJE",
    level: "central",
    sector: "Education abroad",
    tags: ["study_abroad", "scholarship"],
    summary:
      "Fully-funded Master's / PhD study abroad for Scheduled Caste students — covers tuition, maintenance and travel expenses for up to 4 years.",
    benefit: "Full tuition fee (up to ₹38.2L), monthly maintenance (₹15,400–₹2,000+ band), one-time passage and contingency grants.",
    loanWindow: undefined,
    eligibilityText: "SC student with admission to an approved foreign university for Master's/PhD, family income ≤ ₹8L.",
    documents: ["community_certificate", "income_certificate", "education_certificates", "bank_passbook", "photo"],
    applicationRoute: "Apply online at the National Overseas Scholarship portal during the annual window (usually Feb–Apr).",
    officialSource: "Ministry of Social Justice & Empowerment",
    sourceUrl: "https://www.nosmsje.gov.in",
    helpdesk: "NOS helpdesk (MoSJE) / state social welfare office",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("category", "eq", "SC", 30, "SC community"),
      r("annualFamilyIncome", "lte", 800000, 20, "Family income within the ₹8L ceiling"),
      r("firstGraduate", "truthy", undefined, 10, "Graduate moving to Master's / PhD (first-generation learners priority)"),
    ],
  },
  {
    id: "tn_overseas",
    name: "TN Overseas Scholarship — First Generation Graduates",
    department: "Government of Tamil Nadu · Higher Education",
    level: "state",
    sector: "Education abroad",
    tags: ["study_abroad", "scholarship"],
    summary:
      "Tamil Nadu's own overseas scholarship for first-generation graduates from SC/ST/OBC/minority communities pursuing Master's or PhD abroad.",
    benefit: "Tuition and living support for one/two-year Master's and doctoral programmes abroad, for students whose parents have no graduate degree.",
    loanWindow: undefined,
    eligibilityText: "Tamil Nadu resident, first-generation graduate (neither parent a graduate), admitted abroad, family income ≤ ₹6L.",
    documents: ["education_certificates", "community_certificate", "income_certificate", "bank_passbook", "photo"],
    applicationRoute: "Application through the TN Higher Education department / state scholarship portal when the annual notification opens.",
    officialSource: "Higher Education Dept · Govt. of Tamil Nadu",
    sourceUrl: "https://www.tn.gov.in",
    helpdesk: "State scholarship cell, Chennai",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("state", "eq", "Tamil Nadu", 25, "Resident of Tamil Nadu"),
      r("firstGraduate", "truthy", undefined, 20, "First-generation graduate (neither parent a graduate)"),
      r("category", "nin", ["General"], 10, "Reserved / minority communities"),
      r("annualFamilyIncome", "lte", 600000, 10, "Family income within ₹6L"),
    ],
  },
  {
    id: "nsp",
    name: "NSP — Post-Matric Scholarship (Central/State)",
    department: "Ministry of Education · NSP",
    level: "central",
    sector: "Education",
    tags: ["scholarship", "higher_education"],
    summary:
      "The National Scholarship Portal single-window for both central and state post-matric scholarships for SC/ST/OBC/EBC students — hostel charges, maintenance and tuition assistance.",
    benefit: "Tuition + maintenance allowance (₹350–₹750/month for day scholars) + special coaching support for competitive exams.",
    loanWindow: undefined,
    eligibilityText: "SC/ST/OBC/EBC students (and minorities under state schemes) from Class 11 to PhD, with income certificates per scheme band.",
    documents: ["community_certificate", "income_certificate", "education_certificates", "bank_passbook", "photo"],
    applicationRoute: "Create an account at scholarships.gov.in and apply before the annual deadline (usually Oct–Dec).",
    officialSource: "National Scholarship Portal",
    sourceUrl: "https://scholarships.gov.in",
    helpdesk: "NSP helpdesk 0120-6619540 / state nodal officer",
    awareness: "known",
    verifiedDate: "2026-08",
    rules: [
      r("category", "in", ["SC", "ST", "OBC", "EBC"], 25, "SC/ST/OBC/EBC community"),
      r("annualFamilyIncome", "lte", 250000, 20, "Family income within the ₹2.5L ceiling for several bands"),
      r("firstGraduate", "truthy", undefined, 10, "Post-matric student (first-generation learners priority)"),
    ],
  },
  {
    id: "yasasvi",
    name: "PM YASASVI — Scholarships for OBC/EBC (Top Class + Hostels)",
    department: "Ministry of Social Justice · MoSJE",
    level: "central",
    sector: "Education",
    tags: ["scholarship", "higher_education"],
    summary:
      "Lesser-known umbrella for OBC/EBC/DNT students: Top Class Education for OBC (₹75k–₹1.25L/yr in top institutions) and hostel subsidies for those studying away from home.",
    benefit: "Up to ₹1.25L/year tuition, books and living allowance for OBC Top Class scholars; hostel maintenance support for EBC students.",
    loanWindow: undefined,
    eligibilityText: "OBC/EBC/DNT student, family income ≤ ₹2.5L (per current bands), admitted to a recognised institution.",
    documents: ["community_certificate", "income_certificate", "education_certificates", "photo"],
    applicationRoute: "Apply through the National Scholarship Portal (scholarships.gov.in) under the YASASVI schemes.",
    officialSource: "Ministry of Social Justice & Empowerment",
    sourceUrl: "https://scholarships.gov.in",
    helpdesk: "State social welfare office / NSP helpdesk",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("category", "in", ["OBC", "EBC", "DNT"], 30, "OBC/EBC/DNT community"),
      r("annualFamilyIncome", "lte", 250000, 20, "Family income within the ₹2.5L ceiling"),
    ],
  },
  {
    id: "kcc",
    name: "Kisan Credit Card (KCC)",
    department: "NABARD · Banks",
    level: "central",
    sector: "Agriculture finance",
    tags: ["agriculture", "farming_equipment", "business_loan"],
    summary:
      "A revolving credit card for farmers and farmer-producers — crop loans, farm machinery, dairy and allied activities; includes animal-husbandry and fisheries components.",
    benefit: "Collateral-free crop loan limits, 4% p.a. effective interest (3% subvention + 1% prompt-repayment bonus), ₹3L limit for small/marginal farmers.",
    loanWindow: { min: 0.05, max: 3, rate: 4, subsidy: 0, tenureMax: 5 },
    eligibilityText: "Farmer / cultivator / agricultural worker with a landholding, tenant farmers and SHG farmer groups included.",
    documents: ["land_documents", "aadhaar", "bank_passbook", "photo"],
    applicationRoute: "Any bank branch (scheduled bank, RRB) that offers KCC; KCC camps run seasonally.",
    officialSource: "NABARD / RBI",
    sourceUrl: "https://www.nabard.org",
    helpdesk: "Your bank branch / NABARD district office",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("ownsLand", "truthy", undefined, 15, "You own/lease cultivable land"),
      r("isFarmer", "truthy", undefined, 10, "You are a farmer or agricultural worker"),
      r("interestedFarming", "truthy", undefined, 10, "Interest in farming / allied activity"),
      r("age", "gte", 18, 10, "You are at least 18 years old"),
    ],
  },
  {
    id: "smam_chc",
    name: "SMAM — Custom Hiring Centres (Farm Mechanisation)",
    department: "Ministry of Agriculture · DAC&FW",
    level: "central",
    sector: "Agriculture equipment",
    tags: ["farming_equipment", "agriculture", "start_business"],
    summary:
      "A lesser-known route: start a machine-rental business! 40% financial assistance (up to ₹10L) to groups/women/SHGs who set up a Custom Hiring Centre of farm machinery — you rent machines to local farmers.",
    benefit: "Up to 40% subsidy (max ₹10L) on machinery for entrepreneurs and farmer groups; 100% scheme funding for North-East/special states.",
    loanWindow: { min: 2, max: 18, rate: 5, subsidy: 40, tenureMax: 5 },
    eligibilityText: "Farmer groups, FPOs, SHGs and individual farmers; women-led groups get priority under the scheme guidelines.",
    documents: ["business_plan", "land_documents", "income_certificate", "udyam"],
    applicationRoute: "Project proposal via the District Agriculture Officer / State Agriculture Department.",
    officialSource: "DAC&FW · Ministry of Agriculture",
    sourceUrl: "https://www.agricoop.nic.in",
    helpdesk: "District Agriculture Officer",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("interestedFarming", "truthy", undefined, 20, "Interest in farm mechanisation / agri services"),
      r("ownsLand", "truthy", undefined, 10, "Landholding to base the machinery"),
      r("isFarmer", "truthy", undefined, 10, "Farming background helps"),
      r("annualFamilyIncome", "lte", 400000, 10, "Smallholder band for priority subsidy"),
    ],
  },
  {
    id: "pmay",
    name: "PMAY-U — Pradhan Mantri Awas Yojana (Urban)",
    department: "Ministry of Housing & Urban Affairs",
    level: "central",
    sector: "Housing",
    tags: ["housing", "family_benefits"],
    summary:
      "Housing for All: interest subsidy of 6.5% on home loans up to ₹6 lakh for EWS/LIG families (up to ₹2.67L saved), or direct cash support under the Self-Help group vertical.",
    benefit: "Credit-linked subsidy: 6.5% interest subvention on loans up to ₹6L for 20 years; ₹1.5L assistance for beneficiaries under other verticals.",
    loanWindow: { min: 1, max: 6, rate: 6.5, subsidy: 0, tenureMax: 20 },
    eligibilityText: "EWS (income ≤ ₹3L) or LIG (≤ ₹6L), no pucca house anywhere in India, not covered by other housing schemes.",
    documents: ["aadhaar", "income_certificate", "land_documents", "bank_passbook"],
    applicationRoute: "Register on the PMAY-U portal, or in TN through the City-level Technical Cell / ULBs.",
    officialSource: "MoHUA · PMAY-U",
    sourceUrl: "https://pmay-urban.gov.in",
    helpdesk: "City-level nodal officer / PMAY-U helpline",
    awareness: "known",
    verifiedDate: "2026-08",
    rules: [
      r("annualFamilyIncome", "lte", 300000, 25, "EWS income band (≤ ₹3L)"),
      r("ownsLand", "falsy", undefined, 15, "No pucca house / landholding — you qualify as shelterless"),
      r("gender", "eq", "female", 5, "Woman-headed household gets priority"),
      r("hasDisability", "truthy", undefined, 5, "Persons with disabilities get priority"),
    ],
  },
  {
    id: "kalaignar_kanavu",
    name: "Kalaignar Kanavu Illam (TN Rural Housing)",
    department: "Government of Tamil Nadu · Rural Development",
    level: "state",
    sector: "Housing",
    tags: ["housing", "family_benefits"],
    summary:
      "Tamil Nadu's rural housing scheme — house construction assistance of ₹3.5 lakh (in phases) for landless and land-owning rural families below the poverty line.",
    benefit: "₹3.5L construction assistance in four phases (₹1.6L upfront vertical) for rural hut-dwellers and landless labourers.",
    loanWindow: undefined,
    eligibilityText: "TN rural family with a thatched / kutcha house or living on leased land; priority to SC/ST, landless agricultural labourers and PwD.",
    documents: ["land_documents", "income_certificate", "aadhaar", "photo"],
    applicationRoute: "Gram panchayat / village assistant (VAO) — beneficiary list is prepared at the panchayat level.",
    officialSource: "Rural Development Dept · Govt. of Tamil Nadu",
    sourceUrl: "https://www.tn.gov.in",
    helpdesk: "Village panchayat / block development office",
    awareness: "hidden",
    verifiedDate: "2026-08",
    rules: [
      r("state", "eq", "Tamil Nadu", 25, "Rural family in Tamil Nadu"),
      r("annualFamilyIncome", "lte", 300000, 20, "Family income within the BPL band"),
      r("ownsLand", "truthy", undefined, 10, "Owns a plot to construct (or leased land)"),
      r("category", "in", ["SC", "ST"], 5, "SC/ST households get priority"),
      r("hasDisability", "truthy", undefined, 5, "PwD households get priority"),
    ],
  },
  {
    id: "adip",
    name: "ADIP — Assistance to Disabled Persons (Aids & Appliances)",
    department: "Ministry of Social Justice · NIEPMD",
    level: "central",
    sector: "Disability & rehabilitation",
    tags: ["disability_support", "financial_assistance"],
    summary:
      "Free assistive devices — wheelchairs, hearing aids, tricycles, prosthetics — for persons with disabilities through district camps; includes support devices needed for self-employment activities.",
    benefit: "Free assistive aids/equipment (up to ₹10k, 90% subsidy for BPL) delivered through district-level assessment camps.",
    loanWindow: undefined,
    eligibilityText: "Person with disability (certificate), priority to BPL families; applications through district welfare offices.",
    documents: ["disability_certificate", "income_certificate", "aadhaar", "photo"],
    applicationRoute: "District Disability Rehabilitation Centre / social welfare office — camps are held throughout the year.",
    officialSource: "Ministry of Social Justice & Empowerment",
    sourceUrl: "https://sjms.nic.in",
    helpdesk: "District Disability Rehabilitation Centre",
    awareness: "lesser",
    verifiedDate: "2026-08",
    rules: [
      r("hasDisability", "truthy", undefined, 30, "You hold a disability certificate"),
      r("annualFamilyIncome", "lte", 200000, 20, "BPL family gets the 90% subsidy band"),
      r("category", "nin", ["General"], 5, "Reserved category priority"),
    ],
  },
];

export const DEMO_SCHEME_NAMES = SCHEME_SEED.map((s) => s.name);